export const RECOMMENDATION_LIMIT = 10;

export const BODY_PART_OPTIONS = [
  'Abductors & Glute Medius',
  'Abs',
  'Adductors',
  'Athletic & Agility',
  'Biceps',
  'Calves',
  'Chest',
  'Deep Core',
  'Forearms & Grip',
  'Full Body Conditioning',
  'Full Body Strength',
  'Glutes',
  'Hamstrings',
  'Hip Flexors',
  'Lower Back',
  'Mobility & Recovery',
  'Neck',
  'Obliques',
  'Quadriceps',
  'Rotator Cuff',
  'Serratus',
  'Shoulders',
  'Traps',
  'Triceps',
  'Upper Back',
];

export const DIFFICULTY_OPTIONS = [
  'Advanced',
  'Beginner',
  'Intermediate',
];

export const EQUIPMENT_OPTIONS = [
  'Ab Crunch Machine',
  'Agility Ladder',
  'Ankle Strap',
  'Barbell',
  'Bench',
  'Cable Machine',
  'Calf Raise Machine',
  'Decline Bench',
  'Dumbbell',
  'Dumbbells',
  'EZ Bar',
  'Foam Roller',
  'GHD Machine',
  'Hammer',
  'Hip Abduction Machine',
  'Hip Adduction Machine',
  'Kettlebell',
  'Landmine',
  'Leg Curl Machine',
  'Leg Extension Machine',
  'Neck Harness',
  'Parallettes',
  'Plyometric Box',
  'Pull-Up Bar',
  'Rack',
  'Resistance Band',
  'Rope',
  'Row Machine',
  'Sandbag',
  'Slider',
  'Smith Machine',
  'Squat Rack',
  'Towel',
  'Weight Plates',
  'Wrist Roller',
];

export const GOAL_OPTIONS = [
  'Activation',
  'Agility',
  'Athleticism',
  'Balance',
  'Conditioning',
  'Coordination',
  'Core Stability',
  'Core Strength',
  'Endurance',
  'Grip Strength',
  'Hypertrophy',
  'Mobility',
  'Movement Practice',
  'Power',
  'Recovery',
  'Rehabilitation',
  'Shoulder Health',
  'Shoulder Stability',
  'Strength',
  'Warm-Up',
];
